### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by i-zenin** [lionheart/pinboard.py#11]
```
$ pinboard tags
Tag               Count 
Traceback (most recent call last):
  File "/usr/bin/pinboard", line 358, in <module>
    handler.run()
  File "/usr/bin/pinboard", line 280, in run
    command_map[self.namespace.subparser]()
  File "/usr/bin/pinboard", line 189, in _tags_action
    self._call_api_and_catch_exceptions(self.pinboard.tags.get, handler)
  File "/usr/bin/pinboard", line 88, in _call_api_and_catch_exceptions
    value = handler(json_response)
  File "/usr/bin/pinboard", line 186, in handler
    for tag, count in response.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

Arch Linux, Python 3.6.4, pinboard.py 2.1.2

**Comment by dlo** [comment]
Thanks @the0 for the report. Just updated a fix and pushed to PyPi. 🍻
