### ISSUE TITLE
TypeError: the JSON object must be str, not 'HTTPResponse' in pinboard.py

### ISSUE THREAD

**Issue by flowgunso** [lionheart/pinboard.py#12]
I am having an error when using any _pinboard.posts_ functions. This issue happens with _pinboard>=2_ (tested with _2.0.3_ and _2.1.4_). This issue __does not__ happen with _pinboard<2_ and _python2_. 

The traceback is always the following:
```
[2018-06-11 15:07:47,131] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello_world
    print(pb.posts.get(tag="wishlist"))
  File "venv/lib/python3.5/site-packages/pinboard/pinboard.py", line 198, in __call__
    json_response = json.load(response)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

From what I could read at [StackOverflow](https://stackoverflow.com/a/6862922/4390063), the issue may involve _urllib_ and bytes encoding.

I've solved this problem in a venv by replacing:
```
json_response = json.load(response)
```
with:
```
decoded_reponse = response.read().decode('utf-8')
json_response = json.loads(decoded_reponse)
```

Another solution could be to use a more recent HTTP module.

**Comment by flowgunso** [comment]
Most likely, this was an environment issue on my side.
I've tested with a clean Docker environment and it works.
