### ISSUE TITLE
installation fails on Windows

### ISSUE THREAD

**Issue by toyg** [lionheart/pinboard.py#9]
Output when trying to install on Windows (Python 3.6):

```
(venv) C:\Dev\scrapetube>pip install "pinboard>=2.0"
Collecting pinboard>=2.0
  Using cached pinboard-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GIACOM~1.LAC\AppData\Local\Temp\pip-build-kq3vnhn0\pinboard\setup.py", line 30, in <module>
        long_description = file.read()
      File "c:\dev\scrapetube\venv\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5829: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\GIACOM~1.LAC\AppData\Local\Temp\pip-build-kq3vnhn0\pinboard\
```

Python version: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by toyg** [comment]
Looking at setup.py, when trying to read README.rst (or any other file elsewhere) you should use codecs.open() and pass the encoding parameter to it. That's the safest way to read data in a py2/py3 cross-compatible way.

**Comment by toyg** [comment]
Have a look at #10 . Tested working on py3.6, but I'm pretty confident it will be fine on any 2.3+ version too.

**Comment by dlo** [comment]
#10 was merged, thanks again @toyg.
